####################################################################################
####################################################################################
# DEV DOCS SITE CONFIG
#
# Run with args:
#
#  e.g. make HUGO_ARGS="--config config.toml,config.dev.toml" prod-docker-serve
#
# or make DOCKER_BUILD_ARGS="-e HUGO_BASEURL=\"http://localhost:8888\"" prod-docker-serve
#
####################################################################################
####################################################################################

#  Will override existing setting if present

#baseURL = "https://docs-staging.corda.net/"

title = "Using CONFIG.DEV.TOML"


[params]
# specifically set this in dev only to add an icon to launch the file in vscode
# not sure how to trigger for other editors (yet), but I know vscode:// is cross
# platform if installed
# do not delete....
siteroot = "Override on cmd line using HUGO_PARAMS_SITEROOT=$(pwd) hugo serve"
vscode = true
