# When built, then this is used, but we inject it
# at build time using Hugo env-vars.
baseURL = "/"

# Nice stuff...
title = "R3 Documentation"

# Of course...
theme = ['doks']

# i18n
defaultContentLanguage = "en"
# ...so that en docs are just in /docs/... rather than /en/docs/...
defaultContentLanguageInSubdir = false
contentDir = "content/"

# so that 'docs' doesn't appear as 'docss' etc.
pluralizeListTitles = false

# we want old-style a/b/c.html
uglyurls = true

# Change to error eventually.
refLinksErrorLevel = "ERROR"

# Don't care about these.
disableKinds = ["taxonomy", "taxonomyTerm"]

# See https://help.farbox.com/pygments.html
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsStyle = "emacs"

# https://gohugo.io/variables/git/
enableGitInfo = true

# GA was added here: /themes/hugo-r3-theme/scripts/vendor/googleanalytics.js
# We are NOT using the built-in Hugo functionality commented out below
# https://gohugo.io/templates/internal/#google-analytics
googleAnalytics = "283616090"



# https://gohugo.io/getting-started/configuration-markup#highlight
[markup]
[markup.highlight]
style = "tango"


[markup.goldmark]
[markup.goldmark.renderer]
#  We have lots of inline HTML so need to render it.
#  TODO:  replace with shortcodes.
unsafe = true


#  We're not using this?
[permalinks]
blog = "/blog/:section/:year/:month/:day/:slug/"


# Any params set in here override the ones above for that particular site (one site = one lang).
[languages]
[languages.en]
description  = "R3 Documentation"
languageName = "English"
# Weight used for sorting.
weight = 10
#
#[languages.fr]
#contentDir = "content/fr"
#languageName = "Fran√ßais"
#weight = 20
#language_alternatives = ["en"]
#
#[languages.de]
#languageName = "Deutsche"
#weight = 30
#language_alternatives = ["en"]


[params]
github_repository = "https://github.com/corda/corda-docs-portal"

twitter = "cordablockchain"
slack = "https://slack.corda.net/"
github = "corda"
stackoverflow = "corda"

#  Cue bikeshedding
default_tab = "java"

ogimage = "/images/png/corda.png"

# hack - these values are asigned in global.html
algolia_appId = "UX2KMUWFAL"
algolia_apiKey = "d30af47c430efcbae42aa7e855dbf164"
algolia_index = "crawler_docs.r3.com"

googleTagManagerID = "G-NCYRYSGJ7C"

[module]
  [[module.mounts]]
    source = "node_modules/flexsearch"
    target = "assets/js/vendor/flexsearch"
  [[module.mounts]]
    source = "node_modules/katex"
    target = "assets/js/vendor/katex"
