
[[social]]
  name = "Corda Slack"
  pre = "<svg width=\"24\" height=\"24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M5.042 15.166a2.527 2.527 0 01-2.52 2.521A2.527 2.527 0 010 15.166a2.527 2.527 0 012.521-2.521h2.521v2.52zM6.312 15.166a2.527 2.527 0 012.521-2.521 2.527 2.527 0 012.522 2.52v6.314a2.527 2.527 0 01-2.522 2.52 2.527 2.527 0 01-2.52-2.52v-6.313zM8.833 5.042a2.527 2.527 0 01-2.52-2.52A2.527 2.527 0 018.832 0a2.527 2.527 0 012.522 2.521v2.521H8.833zM8.834 6.31a2.527 2.527 0 012.521 2.522 2.527 2.527 0 01-2.521 2.521H2.521A2.527 2.527 0 010 8.832 2.527 2.527 0 012.521 6.31h6.313zM18.957 8.832a2.527 2.527 0 012.521-2.521 2.527 2.527 0 012.521 2.52 2.527 2.527 0 01-2.521 2.522h-2.521V8.832zM17.687 8.834a2.527 2.527 0 01-2.521 2.521 2.527 2.527 0 01-2.521-2.521V2.521A2.527 2.527 0 0115.165 0a2.527 2.527 0 012.522 2.521v6.313zM15.166 18.955a2.527 2.527 0 012.521 2.522 2.527 2.527 0 01-2.521 2.52 2.527 2.527 0 01-2.521-2.52v-2.522h2.52zM15.166 17.687a2.527 2.527 0 01-2.521-2.521 2.527 2.527 0 012.52-2.521h6.314A2.527 2.527 0 0124 15.165a2.527 2.527 0 01-2.521 2.522h-6.313z\" fill=\"#FCFCFC\"/></svg>"
  url = "https://slack.corda.net/"
  weight = 10

[[social]]
  name = "Corda Blockchain Twitter"
  pre = "<svg width=\"24\" height=\"20\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M24 2.644c-.735.29-1.84.418-2.619.349.447-.316 1.582-1.24 1.845-2.67-1.164.76-2.794 1.077-3.49 1.066a5.008 5.008 0 00-3.09-1.066 5.032 5.032 0 00-5.033 5.031c0 .262.026.517.065.768-2.006-.036-6.467-.814-10.13-5.026-2 3.42.455 5.547 1.549 6.486-1 .547-2.323-.658-2.323-.658s-.064 4.059 4.11 4.884c-.706.53-1.949.482-2.561.095.844 3.287 4.41 3.475 4.645 3.475-2.161 1.597-4.162 2.04-6.968 1.976 2.436 1.839 5.275 2.293 7.742 2.323 1.938.022 3.717-.377 5.127-.964 5.87-2.442 8.808-7.582 8.808-13.359 0-.159-.009-.315-.023-.47 1.086-.408 1.869-1.326 2.346-2.24z\" fill=\"#FCFCFC\"/></svg>"
  url = "https://twitter.com/cordablockchain"
  weight = 20

[[social]]
  name = "Corda Medium"
  pre = "<svg width=\"40\" height=\"24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><g clip-path=\"url(#clip0)\" fill=\"#FCFCFC\"><path d=\"M11.33 23.33c6.256 0 11.329-5.073 11.329-11.33S17.586.67 11.329.67 0 5.744 0 12s5.072 11.33 11.33 11.33zM29.401 22.964c3.129 0 5.665-4.909 5.665-10.964 0-6.055-2.536-10.964-5.665-10.964-3.128 0-5.664 4.909-5.664 10.964 0 6.055 2.536 10.964 5.665 10.964zM38.008 21.502c1.09 0 1.974-4.254 1.974-9.502 0-5.248-.884-9.502-1.974-9.502-1.09 0-1.973 4.254-1.973 9.502 0 5.248.883 9.502 1.973 9.502z\"/></g><defs><clipPath id=\"clip0\"><path fill=\"#fff\" transform=\"translate(0 .67)\" d=\"M0 0h40v22.659H0z\"/></clipPath></defs></svg>"
  url = "https://medium.com/corda"
  weight = 30

[[social]]
  name = "R3 Developers YouTube"
  pre = "<svg width=\"26\" height=\"18\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M25.7 5.44v-.013c-.127-1.671-.371-2.465-.371-2.465l-.004.006c-.016-.061-.03-.125-.05-.184l-.002-.012h-.001a3.503 3.503 0 00-2.81-2.358V.41C13.262-.495 3.758.38 3.758.38v.011A3.494 3.494 0 00.745 2.635L.74 2.633l-.024.077a3.47 3.47 0 00-.137.493c-.327 1.297-.985 4.8-.235 9.99l-.003-.001.196 1.236c.014.138.036.273.065.407l.01.063.004-.005c.012.054.022.108.037.162l.004.02h.001a3.495 3.495 0 003.181 2.497v.008s7.472.946 18.287 0l.002-.005a3.461 3.461 0 001.38-.363c.012-.006.023-.008.036-.014 1.067-.51 1.52-1.438 1.673-1.841.01-.022.018-.05.027-.077.025-.071.04-.123.04-.123h-.003c.006-.024.014-.04.02-.068l.037-.175a3.66 3.66 0 00.07-.353c.28-1.49.327-2.814.327-2.814h-.004c.224-2.58.13-4.75-.032-6.307zm-15.26 7.491V5.198l6.744 3.867-6.744 3.866z\" fill=\"#FCFCFC\"/></svg>"
  url = "https://www.youtube.com/channel/UCoOuUZatvIC1U65OisCrIKg/featured"
  weight = 40

[[social]]
  name = "R3 Documentation GitHub"
  pre = "<svg width=\"26\" height=\"24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M13.162 0C6.372 0 .865 5.507.865 12.297c0 5.432 3.546 10.034 8.374 11.693.603.076.83-.301.83-.603v-2.113c-3.395.755-4.15-1.66-4.15-1.66-.528-1.433-1.357-1.81-1.357-1.81-1.132-.754.075-.754.075-.754 1.207.075 1.886 1.282 1.886 1.282 1.132 1.886 2.867 1.358 3.546 1.056.075-.83.452-1.358.754-1.66-2.716-.301-5.582-1.357-5.582-6.11 0-1.358.452-2.414 1.282-3.32-.075-.226-.528-1.508.15-3.168 0 0 1.057-.302 3.396 1.282.98-.301 2.037-.377 3.093-.377s2.112.151 3.093.377C18.594 4.828 19.65 5.13 19.65 5.13c.679 1.66.226 2.942.15 3.244a4.88 4.88 0 011.283 3.32c0 4.752-2.867 5.733-5.582 6.035.452.377.83 1.131.83 2.263v3.395c0 .302.226.679.83.603a12.31 12.31 0 008.373-11.693C25.46 5.507 19.952 0 13.162 0z\" fill=\"#FCFCFC\"/></svg>"
  url = "https://www.github.com/corda/corda-docs-portal"
  weight = 45

[[social]]
  name = "R3 Developers GitHub"
  pre = "<svg width=\"26\" height=\"24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M13.162 0C6.372 0 .865 5.507.865 12.297c0 5.432 3.546 10.034 8.374 11.693.603.076.83-.301.83-.603v-2.113c-3.395.755-4.15-1.66-4.15-1.66-.528-1.433-1.357-1.81-1.357-1.81-1.132-.754.075-.754.075-.754 1.207.075 1.886 1.282 1.886 1.282 1.132 1.886 2.867 1.358 3.546 1.056.075-.83.452-1.358.754-1.66-2.716-.301-5.582-1.357-5.582-6.11 0-1.358.452-2.414 1.282-3.32-.075-.226-.528-1.508.15-3.168 0 0 1.057-.302 3.396 1.282.98-.301 2.037-.377 3.093-.377s2.112.151 3.093.377C18.594 4.828 19.65 5.13 19.65 5.13c.679 1.66.226 2.942.15 3.244a4.88 4.88 0 011.283 3.32c0 4.752-2.867 5.733-5.582 6.035.452.377.83 1.131.83 2.263v3.395c0 .302.226.679.83.603a12.31 12.31 0 008.373-11.693C25.46 5.507 19.952 0 13.162 0z\" fill=\"#FCFCFC\"/></svg>"
  url = "https://r3developer.github.io/"
  weight = 50

[[social]]
  name = "R3 LinkedIn"
  pre = "<svg width=\"26\" height=\"24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M.853 7.806h5.38V24H.854V7.806zM3.579 0C1.737 0 .534 1.21.534 2.796c0 1.555 1.168 2.799 2.975 2.799h.034c1.877 0 3.046-1.244 3.046-2.799C6.554 1.21 5.42 0 3.579 0zm15.867 7.426c-2.856 0-4.136 1.57-4.85 2.673V7.806H9.213c.072 1.52 0 16.194 0 16.194h5.383v-9.044c0-.484.036-.967.177-1.314.39-.967 1.276-1.968 2.761-1.968 1.95 0 2.728 1.486 2.728 3.662V24h5.381v-9.286c0-4.974-2.654-7.288-6.197-7.288z\" fill=\"#FCFCFC\"/></svg>"
  url = "https://www.linkedin.com/company/r3cev-llc/"
  weight = 60

[[footer]]
  name = "Terms of Use"
  url = "https://www.r3.com/terms-of-use/"
  weight = 10

[[footer]]
  name = "Privacy Policy"
  url = "https://www.r3.com/privacy-policy/"
  weight = 20

[[footer]]
  name = "Trademark Policy"
  url = "https://www.r3.com/trademark-policy/"
  weight = 30

[[cenm-1-0]]
identifier = "cenm-1-0-concepts-and-overview"
name = "Concepts and Overview"
weight = 10

[[cenm-1-0]]
identifier = "cenm-1-0-configuration"
name = "Configuration"
weight = 200

[[cenm-1-0]]
identifier = "cenm-1-0-enm-releases"
name = "ENM Releases"
weight = 70

[[cenm-1-0]]
identifier = "cenm-1-0-operations"
name = "Operations"
weight = 110

[[cenm-1-0]]
identifier = "cenm-1-0-public-key-infrastructure"
name = "Public Key Infrastructure"
weight = 310

[[cenm-1-1]]
identifier = "cenm-1-1-cenm-releases"
name = "CENM Releases"
weight = 70

[[cenm-1-1]]
identifier = "cenm-1-1-concepts-and-overview"
name = "Concepts and Overview"
weight = 10

[[cenm-1-1]]
identifier = "cenm-1-1-configuration"
name = "Configuration"
weight = 210

[[cenm-1-1]]
identifier = "cenm-1-1-operations"
name = "Operations"
weight = 110

[[cenm-1-1]]
identifier = "cenm-1-1-public-key-infrastructure"
name = "Public Key Infrastructure"
weight = 300

[[cenm-1-2]]
identifier = "cenm-1-2-cenm-releases"
name = "CENM Releases"
weight = 70

[[cenm-1-2]]
identifier = "cenm-1-2-concepts-and-overview"
name = "Concepts and Overview"
weight = 10

[[cenm-1-2]]
identifier = "cenm-1-2-configuration"
name = "Configuration"
weight = 210

[[cenm-1-2]]
identifier = "cenm-1-2-operations"
name = "Operations"
weight = 110

[[cenm-1-2]]
identifier = "cenm-1-2-public-key-infrastructure"
name = "Public Key Infrastructure"
weight = 300

[[cenm-1-2]]
identifier = "cenm-1-2-signing-plugin-samples"
name = "Signing Plugin Samples"
weight = 330

[[cenm-1-3]]
identifier = "cenm-1-3-cenm-releases"
name = "CENM Releases"
weight = 70

[[cenm-1-3]]
identifier = "cenm-1-3-concepts-and-overview"
name = "Concepts and Overview"
weight = 10

[[cenm-1-3]]
identifier = "cenm-1-3-configuration"
name = "Configuration"
weight = 210

[[cenm-1-3]]
identifier = "cenm-1-3-operations"
name = "Operations"
weight = 110

[[cenm-1-3]]
identifier = "cenm-1-3-public-key-infrastructure"
name = "Public Key Infrastructure"
weight = 300

[[cenm-1-3]]
identifier = "cenm-1-3-signing-plugin-samples"
name = "Signing Plugin Samples"
weight = 330

[[cenm-1-4]]
identifier = "cenm-1-4-cenm-releases"
name = "CENM Releases"
weight = 70

[[cenm-1-4]]
identifier = "cenm-1-4-concepts-and-overview"
name = "Concepts and Overview"
weight = 10

[[cenm-1-4]]
identifier = "cenm-1-4-configuration"
name = "Configuration"
weight = 210

[[cenm-1-4]]
identifier = "cenm-1-4-operations"
name = "Operations"
weight = 110

[[cenm-1-4]]
identifier = "cenm-1-4-public-key-infrastructure"
name = "Public Key Infrastructure"
weight = 300

[[cenm-1-4]]
identifier = "cenm-1-4-signing-plugin-samples"
name = "Signing Plugin Samples"
weight = 330

[[cenm-1-5]]
identifier = "cenm-1-5-cenm-releases"
name = "CENM Releases"
weight = 70

[[cenm-1-5]]
identifier = "cenm-1-5-concepts-and-overview"
name = "Concepts and Overview"
weight = 10

[[cenm-1-5]]
identifier = "cenm-1-5-configuration"
name = "Configuration"
weight = 210

[[cenm-1-5]]
identifier = "cenm-1-5-operations"
name = "Operations"
weight = 110

[[cenm-1-5]]
identifier = "cenm-1-5-public-key-infrastructure"
name = "Public Key Infrastructure"
weight = 300

[[cenm-1-5]]
identifier = "cenm-1-5-signing-plugin-samples"
name = "Signing Plugin Samples"
weight = 330

[[corda-enterprise-4-5]]
identifier = "corda-enterprise-4-5-upgrading-and-tools"
name = "Upgrading CorDapps and Nodes"
weight = 10

[[corda-enterprise-4-5]]
identifier = "corda-enterprise-4-5-notaries"
name = "Corda Notaries"
weight = 35

[[corda-enterprise-4-5]]
identifier = "corda-enterprise-4-5-corda-networks"
name = "Corda Networks"
weight = 40

[[corda-enterprise-4-5]]
identifier = "corda-enterprise-4-5-corda-nodes-operating"
name = "Operating a Corda Node"
parent = "corda-enterprise-4-5-corda-nodes"
weight = 60

[[corda-enterprise-4-6]]
identifier = "corda-enterprise-4-6-notaries"
name = "Corda Notaries"
weight = 35

[[corda-enterprise-4-6]]
identifier = "corda-enterprise-4-6-corda-networks"
name = "Corda Networks"
weight = 40

[[corda-enterprise-4-6]]
identifier = "corda-enterprise-4-6-corda-nodes-operating"
name = "Operating a Corda Node"
parent = "corda-enterprise-4-6-corda-nodes"
weight = 60

[[corda-enterprise-4-7]]
identifier = "corda-enterprise-4-7-notaries"
name = "Corda Notaries"
weight = 35

[[corda-enterprise-4-7]]
identifier = "corda-enterprise-4-7-corda-networks"
name = "Corda Networks"
weight = 40

[[corda-enterprise-4-7]]
identifier = "corda-enterprise-4-7-corda-nodes-operating"
name = "Operating a Corda Node"
parent = "corda-enterprise-4-7-corda-nodes"
weight = 60

[[corda-enterprise-4-8]]
identifier = "corda-enterprise-4-8-notaries"
name = "Corda Notaries"
weight = 35

[[corda-enterprise-4-8]]
identifier = "corda-enterprise-4-8-corda-networks"
name = "Corda Networks"
weight = 40

[[corda-enterprise-4-8]]
identifier = "corda-enterprise-4-8-corda-nodes-operating"
name = "Operating a Corda Node"
parent = "corda-enterprise-4-8-corda-nodes"
weight = 60

[[corda-enterprise-4-8]]
identifier = "corda-enterprise-4-8-notaries"
name = "Corda Notaries"
weight = 35

[[corda-enterprise-4-8]]
identifier = "corda-enterprise-4-8-corda-networks"
name = "Corda Networks"
weight = 40

[[corda-enterprise-4-8]]
identifier = "corda-enterprise-4-8-corda-nodes-operating"
name = "Operating a Corda Node"
parent = "corda-enterprise-4-8-corda-nodes"
weight = 60

[[corda-enterprise-4-9]]
identifier = "corda-enterprise-4-9-notaries"
name = "Corda Notaries"
weight = 35

[[corda-enterprise-4-9]]
identifier = "corda-enterprise-4-9-corda-networks"
name = "Corda Networks"
weight = 40

[[corda-enterprise-4-9]]
identifier = "corda-enterprise-4-9-corda-nodes-operating"
name = "Operating a Corda Node"
parent = "corda-enterprise-4-9-corda-nodes"
weight = 60

[[corda-enterprise-4-9]]
identifier = "corda-enterprise-4-9-notaries"
name = "Corda Notaries"
weight = 35

[[corda-enterprise-4-9]]
identifier = "corda-enterprise-4-9-corda-networks"
name = "Corda Networks"
weight = 40

[[corda-enterprise-4-9]]
identifier = "corda-enterprise-4-9-corda-nodes-operating"
name = "Operating a Corda Node"
parent = "corda-enterprise-4-9-corda-nodes"
weight = 60

[[corda-enterprise-4-10]]
identifier = "corda-enterprise-4-10-notaries"
name = "Corda Notaries"
weight = 35

[[corda-enterprise-4-10]]
identifier = "corda-enterprise-4-10-corda-networks"
name = "Corda Networks"
weight = 40

[[corda-enterprise-4-10]]
identifier = "corda-enterprise-4-10-corda-nodes-operating"
name = "Operating a Corda Node"
parent = "corda-enterprise-4-10-corda-nodes"
weight = 60

[[corda-enterprise-4-10]]
identifier = "corda-enterprise-4-10-notaries"
name = "Corda Notaries"
weight = 35

[[corda-enterprise-4-10]]
identifier = "corda-enterprise-4-10-corda-networks"
name = "Corda Networks"
weight = 40

[[corda-enterprise-4-10]]
identifier = "corda-enterprise-4-10-corda-nodes-operating"
name = "Operating a Corda Node"
parent = "corda-enterprise-4-10-corda-nodes"
weight = 60

[[corda-community-4-10]]
identifier = "corda-community-4-10-upgrading"
name = "Upgrading CorDapps and nodes"
weight = 15

[[corda-community-4-10]]
identifier = "corda-community-4-10-corda-api"
name = "Corda API"
weight = 17

[[corda-community-4-10]]
identifier = "corda-community-4-10-development"
name = "Development"
weight = 20

[[corda-community-4-10]]
identifier = "corda-community-4-10-operations"
name = "Operations"
weight = 30

[[corda-community-4-10]]
identifier = "corda-community-4-10-contributing-index"
name = "Participate"
weight = 500

[[corda-5-beta]]
identifier = "corda-5-beta-deploy-troubleshoot"
parent = "corda-5-beta-deploy"
name = "Troubleshooting"
weight = 6000

[[corda-5-beta]]
identifier = "corda-5-beta-tutorials-deploy"
parent = "corda-5-beta-deploy"
name = "Deployment Tutorials"
weight = 9000

[[corda-5-beta]]
identifier = "corda-5-beta-tutorials-operate"
parent = "corda-5-beta-operate"
name = "Operating Tutorials"
weight = 1000

[[corda-5-beta]]
identifier = "corda-5-beta-tutorials-deploy-dynamic"
parent = "corda-5-beta-onboarding-tutorials"
name = "Dynamic Networks"
weight = 2000

[[corda-5-beta]]
identifier = "corda-5-beta-tutorials-deploy-static"
parent = "corda-5-beta-onboarding-tutorials"
name = "Static Networks"
weight = 1000

[[corda-5-beta]]
identifier = "corda-5-beta-tutorials-develop"
parent = "corda-5-beta-develop"
name = "Development Tutorials"
weight = 9000

[[corda-5-beta]]
identifier = "corda-5-beta-operate-rest-ref"
name = "REST API Reference"
weight = 5050
url = 'https://docs.r3.com/en/platform/corda/5.0-beta/rest-api/C5_OpenAPI.html'

[[corda-5-beta]]
identifier = " "
parent = "corda-5-beta-start"
name = "UTXO Ledger Example CorDapp"
weight = 5000

#keeping for when we decide to move CDL to a standalone sub-section with a LHS menu
#[[tools-cdl]]
#identifier = "tools-cdl"
#name = "CorDapp Design Language (CDL)"
#weight = 100

#new platform section here
#the homepage menu creates a left hand side menu inside all the landing pages
#if an entry has a URL property, it is to artificially add the document into a second menu

#this entry is required to create a link to the corda docs in the homepage menu
[[homepage]]
identifier = "platform-corda-comm"
parent = "platform-corda-4"
url = "/en/platform/corda/4.10/community.html"
name = "Corda Community "
weight = 100

#this entry is required to create a link to the corda ent docs in the homepage menu
[[homepage]]
identifier = "platform-corda-ent"
parent = "platform-corda-4"
url = "/en/platform/corda/4.10/enterprise.html"
name = "Corda Enterprise"
weight = 200

#this entry is required to create a link to the cenm docs in the homepage menu
[[homepage]]
identifier = "platform-corda-cenm"
parent = "platform-corda-4"
url = "/en/platform/corda/1.5/cenm.html"
name = "Corda Enterprise Network Manager"
weight = 300

#the following samples entries are for visual/demo purposes only and serve as links to github samples in the homepage menu
[[homepage]]
identifier = "sample-1"
parent = "homepage-samples"
name = "Sample 1"
url = "https://github.com/"
weight = 100

[[homepage]]
identifier = "sample-2"
parent = "homepage-samples"
name = "Sample 2"
url = "https://github.com/"
weight = 200

[[homepage]]
identifier = "sample-3"
parent = "homepage-samples"
name = "Sample 3"
url = "https://github.com/"
weight = 300

#the following apps links are a little redundant but they create menu entries for homepage that also link to the apps docs menu
[[homepage]]
identifier = "apps-biab"
parent = "homepage-apps"
name = "Bank in a box"
url = "/en/apps/bankinabox/bank-index.html"
weight = 100

#the following platform entries are non-document menu entries, they could be replaced with documents but new content would have to be created
[[homepage]]
identifier = "platform-corda-4"
parent = "homepage-corda"
name = "Corda 4"
weight = 200

[[homepage]]
identifier = "platform-corda-5"
parent = "homepage-corda"
name = "Corda 5"
weight = 100
