[[cenm-1-0]]
identifier = "cenm-1-0-concepts-and-overview"
name = "Concepts and Overview"
weight = 10

[[cenm-1-0]]
identifier = "cenm-1-0-configuration"
name = "Configuration"
weight = 200

[[cenm-1-0]]
identifier = "cenm-1-0-enm-releases"
name = "ENM Releases"
weight = 70

[[cenm-1-0]]
identifier = "cenm-1-0-operations"
name = "Operations"
weight = 110

[[cenm-1-0]]
identifier = "cenm-1-0-public-key-infrastructure"
name = "Public Key Infrastructure"
weight = 310

[[cenm-1-0]]
identifier = "cenm-1-0-tools-and-utilities"
name = "Tools & Utilities"
weight = 260

[[cenm-1-1]]
identifier = "cenm-1-1-cenm-releases"
name = "CENM Releases"
weight = 70

[[cenm-1-1]]
identifier = "cenm-1-1-concepts-and-overview"
name = "Concepts and Overview"
weight = 10

[[cenm-1-1]]
identifier = "cenm-1-1-configuration"
name = "Configuration"
weight = 210

[[cenm-1-1]]
identifier = "cenm-1-1-operations"
name = "Operations"
weight = 110

[[cenm-1-1]]
identifier = "cenm-1-1-public-key-infrastructure"
name = "Public Key Infrastructure"
weight = 300

[[cenm-1-1]]
identifier = "cenm-1-1-tools-and-utilities"
name = "Tools & Utilities"
weight = 270

[[cenm-1-2]]
identifier = "cenm-1-2-cenm-releases"
name = "CENM Releases"
weight = 70

[[cenm-1-2]]
identifier = "cenm-1-2-concepts-and-overview"
name = "Concepts and Overview"
weight = 10

[[cenm-1-2]]
identifier = "cenm-1-2-configuration"
name = "Configuration"
weight = 210

[[cenm-1-2]]
identifier = "cenm-1-2-operations"
name = "Operations"
weight = 110

[[cenm-1-2]]
identifier = "cenm-1-2-public-key-infrastructure"
name = "Public Key Infrastructure"
weight = 300

[[cenm-1-2]]
identifier = "cenm-1-2-signing-plugin-samples"
name = "Signing Plugin Samples"
weight = 330

[[cenm-1-2]]
identifier = "cenm-1-2-tools-and-utilities"
name = "Tools & Utilities"
weight = 270

[[cenm-1-3]]
identifier = "cenm-1-3-cenm-releases"
name = "CENM Releases"
weight = 70

[[cenm-1-3]]
identifier = "cenm-1-3-concepts-and-overview"
name = "Concepts and Overview"
weight = 10

[[cenm-1-3]]
identifier = "cenm-1-3-configuration"
name = "Configuration"
weight = 210

[[cenm-1-3]]
identifier = "cenm-1-3-operations"
name = "Operations"
weight = 110

[[cenm-1-3]]
identifier = "cenm-1-3-public-key-infrastructure"
name = "Public Key Infrastructure"
weight = 300

[[cenm-1-3]]
identifier = "cenm-1-3-signing-plugin-samples"
name = "Signing Plugin Samples"
weight = 330

[[cenm-1-3]]
identifier = "cenm-1-3-tools-and-utilities"
name = "Tools & Utilities"
weight = 270

[[corda-enterprise-3-0]]
identifier = "corda-enterprise-3-0-corda-enterprise"
name = "Corda Enterprise"
weight = 10

[[corda-enterprise-3-0]]
identifier = "corda-enterprise-3-0-development"
name = "Development"
weight = 50

[[corda-enterprise-3-0]]
identifier = "corda-enterprise-3-0-operations"
name = "Operations"
weight = 160

[[corda-enterprise-3-0]]
identifier = "corda-enterprise-3-0-other-docs"
parent = "corda-enterprise-3-0-quickstart-index"
name = "Other docs"
weight = 1000

[[corda-enterprise-3-0]]
identifier = "corda-enterprise-3-0-other-documentation"
name = "Other documentation"
weight = 220

[[corda-enterprise-3-0]]
identifier = "corda-enterprise-3-0-release-process-index"
name = "Release Process"
weight = 1010

[[corda-enterprise-3-1]]
identifier = "corda-enterprise-3-1-corda-enterprise"
name = "Corda Enterprise"
weight = 10

[[corda-enterprise-3-1]]
identifier = "corda-enterprise-3-1-development"
name = "Development"
weight = 100

[[corda-enterprise-3-1]]
identifier = "corda-enterprise-3-1-operations"
name = "Operations"
weight = 210

[[corda-enterprise-3-1]]
identifier = "corda-enterprise-3-1-other-docs"
parent = "corda-enterprise-3-1-quickstart-index"
name = "Other docs"
weight = 1000

[[corda-enterprise-3-1]]
identifier = "corda-enterprise-3-1-release-process-index"
name = "Release Process"
weight = 1010

[[corda-enterprise-3-2]]
identifier = "corda-enterprise-3-2-corda-enterprise"
name = "Corda Enterprise"
weight = 10

[[corda-enterprise-3-2]]
identifier = "corda-enterprise-3-2-development"
name = "Development"
weight = 100

[[corda-enterprise-3-2]]
identifier = "corda-enterprise-3-2-operations"
name = "Operations"
weight = 210

[[corda-enterprise-3-2]]
identifier = "corda-enterprise-3-2-other-docs"
parent = "corda-enterprise-3-2-quickstart-index"
name = "Other docs"
weight = 1000

[[corda-enterprise-3-2]]
identifier = "corda-enterprise-3-2-release-process-index"
name = "Release Process"
weight = 1010

[[corda-enterprise-3-3]]
identifier = "corda-enterprise-3-3-corda-enterprise"
name = "Corda Enterprise"
weight = 10

[[corda-enterprise-3-3]]
identifier = "corda-enterprise-3-3-development"
name = "Development"
weight = 100

[[corda-enterprise-3-3]]
identifier = "corda-enterprise-3-3-operations"
name = "Operations"
weight = 210

[[corda-enterprise-3-3]]
identifier = "corda-enterprise-3-3-other-docs"
parent = "corda-enterprise-3-3-quickstart-index"
name = "Other docs"
weight = 1000

[[corda-enterprise-4-0]]
identifier = "corda-enterprise-4-0-corda-enterprise"
name = "Corda Enterprise"
weight = 90

[[corda-enterprise-3-3]]
identifier = "corda-enterprise-3-3-release-process-index"
name = "Release Process"
weight = 1010

[[corda-enterprise-4-0]]
identifier = "corda-enterprise-4-0-development"
name = "Development"
weight = 170

[[corda-enterprise-4-0]]
identifier = "corda-enterprise-4-0-operations"
name = "Operations"
weight = 280

[[corda-enterprise-4-1]]
identifier = "corda-enterprise-4-1-development"
name = "Development"
weight = 70

[[corda-enterprise-4-1]]
identifier = "corda-enterprise-4-1-operations"
name = "Operations"
weight = 180

[[corda-enterprise-4-1]]
identifier = "corda-enterprise-4-1-participate"
name = "Participate"
weight = 270

[[corda-enterprise-4-2]]
identifier = "corda-enterprise-4-2-corda-enterprise"
name = "Corda Enterprise"
weight = 90

[[corda-enterprise-4-2]]
identifier = "corda-enterprise-4-2-development"
name = "Development"
weight = 180

[[corda-enterprise-4-2]]
identifier = "corda-enterprise-4-2-miscellaneous"
name = "Miscellaneous"
weight = 4000

[[corda-enterprise-4-2]]
identifier = "corda-enterprise-4-2-operations"
name = "Operations"
weight = 280

[[corda-enterprise-4-3]]
identifier = "corda-enterprise-4-3-corda-api"
name = "Corda API"
weight = 64

[[corda-enterprise-4-3]]
identifier = "corda-enterprise-4-3-corda-enterprise"
name = "Corda Enterprise"
weight = 80

[[corda-enterprise-4-3]]
identifier = "corda-enterprise-4-3-development"
name = "Development"
weight = 170

[[corda-enterprise-4-3]]
identifier = "corda-enterprise-4-3-miscellaneous"
name = "Miscellaneous"
weight = 520

[[corda-enterprise-4-3]]
identifier = "corda-enterprise-4-3-operations"
name = "Operations"
weight = 430

[[corda-enterprise-4-4]]
identifier = "corda-enterprise-4-4-corda-nodes"
name = "Corda Nodes"
weight = 30

[[corda-enterprise-4-4]]
identifier = "corda-enterprise-4-4-cordapps"
name = "CorDapps"
weight = 20

[[corda-enterprise-4-4]]
identifier = "corda-enterprise-4-4-miscellaneous"
name = "Miscellaneous"
weight = 4000

[[corda-enterprise-4-4]]
identifier = "corda-enterprise-4-4-upgrading-and-tools"
name = "Upgrading and Tools"
weight = 10

[[corda-enterprise-4-4]]
identifier = "corda-enterprise-4-4-corda-networks"
name = "Corda Networks"
weight = 40

[[corda-enterprise-4-5]]
identifier = "corda-enterprise-4-5-upgrading-and-tools"
name = "Upgrading CorDapps and Nodes"
weight = 10

[[corda-enterprise-4-5]]
identifier = "corda-enterprise-4-5-notaries"
name = "Corda Notaries"
weight = 35

[[corda-enterprise-4-5]]
identifier = "corda-enterprise-4-5-corda-networks"
name = "Corda Networks"
weight = 40

[[corda-enterprise-4-5]]
identifier = "corda-enterprise-4-5-corda-nodes-operating"
name = "Operating a Corda Node"
parent = "corda-enterprise-4-5-corda-nodes"
weight = 60

[[corda-os-4-0]]
identifier = "corda-os-4-0-development"
name = "Development"
weight = 40

[[corda-os-4-0]]
identifier = "corda-os-4-0-operations"
name = "Operations"
weight = 150

[[corda-os-4-0]]
identifier = "corda-os-4-0-participate"
name = "Participate"
weight = 240

[[corda-os-4-1]]
identifier = "corda-os-4-1-development"
name = "Development"
weight = 70

[[corda-os-4-1]]
identifier = "corda-os-4-1-operations"
name = "Operations"
weight = 180

[[corda-os-4-1]]
identifier = "corda-os-4-1-participate"
name = "Participate"
weight = 270

[[corda-os-4-3]]
identifier = "corda-os-4-3-development"
name = "Development"
weight = 60

[[corda-os-4-3]]
identifier = "corda-os-4-3-corda-api"
name = "Corda API"
weight = 50

[[corda-os-4-3]]
identifier = "corda-os-4-3-operations"
name = "Operations"
weight = 320

[[corda-os-4-3]]
identifier = "corda-os-4-3-participate"
name = "Participate"
weight = 410

[[corda-os-4-4]]
identifier = "corda-os-4-4-development"
name = "Development"
weight = 20

[[corda-os-4-4]]
identifier = "corda-os-4-4-corda-api"
name = "Corda API"
weight = 15

[[corda-os-4-4]]
identifier = "corda-os-4-4-operations"
name = "Operations"
weight = 40

[[corda-os-4-4]]
identifier = "corda-os-4-4-participate"
name = "Participate"
weight = 410

[[corda-os-4-5]]
identifier = "corda-os-4-5-upgrading"
name = "Upgrading CorDapps and nodes"
weight = 15

[[corda-os-4-5]]
identifier = "corda-os-4-5-corda-api"
name = "Corda API"
weight = 17

[[corda-os-4-5]]
identifier = "corda-os-4-5-development"
name = "Development"
weight = 25

[[corda-os-4-5]]
identifier = "corda-os-4-5-operations"
name = "Operations"
weight = 30

[[corda-os-4-5]]
identifier = "corda-os-4-5-contributing-index"
name = "Participate"
weight = 410
