
[[social]]
  name = "Corda Slack"
  pre = "<svg width=\"24\" height=\"24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M5.042 15.166a2.527 2.527 0 01-2.52 2.521A2.527 2.527 0 010 15.166a2.527 2.527 0 012.521-2.521h2.521v2.52zM6.312 15.166a2.527 2.527 0 012.521-2.521 2.527 2.527 0 012.522 2.52v6.314a2.527 2.527 0 01-2.522 2.52 2.527 2.527 0 01-2.52-2.52v-6.313zM8.833 5.042a2.527 2.527 0 01-2.52-2.52A2.527 2.527 0 018.832 0a2.527 2.527 0 012.522 2.521v2.521H8.833zM8.834 6.31a2.527 2.527 0 012.521 2.522 2.527 2.527 0 01-2.521 2.521H2.521A2.527 2.527 0 010 8.832 2.527 2.527 0 012.521 6.31h6.313zM18.957 8.832a2.527 2.527 0 012.521-2.521 2.527 2.527 0 012.521 2.52 2.527 2.527 0 01-2.521 2.522h-2.521V8.832zM17.687 8.834a2.527 2.527 0 01-2.521 2.521 2.527 2.527 0 01-2.521-2.521V2.521A2.527 2.527 0 0115.165 0a2.527 2.527 0 012.522 2.521v6.313zM15.166 18.955a2.527 2.527 0 012.521 2.522 2.527 2.527 0 01-2.521 2.52 2.527 2.527 0 01-2.521-2.52v-2.522h2.52zM15.166 17.687a2.527 2.527 0 01-2.521-2.521 2.527 2.527 0 012.52-2.521h6.314A2.527 2.527 0 0124 15.165a2.527 2.527 0 01-2.521 2.522h-6.313z\" fill=\"#FCFCFC\"/></svg>"
  url = "https://join.slack.com/t/cordaledger/shared_invite/zt-1t1dsbs9z-23dPsnZGJZaDMK1gLyXxDQ"
  weight = 10

[[social]]
  name = "Corda Blockchain Twitter"
  pre = "<svg width=\"24\" height=\"24\" version=\"1.1\" id=\"Layer_1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" x=\"0px\" y=\"0px\" viewBox=\"0 0 27.1 22\" style=\"enable-background:new 0 0 27.1 22;\" xml:space=\"preserve\"> <style type=\"text/css\">	.st0{fill:#FFFFFF;} </style> <path class=\"st0\" d=\"M2.8,22c0-0.1,0.1-0.1,0.1-0.2c0.3-0.4,0.6-0.7,0.9-1.1c1.4-1.6,2.8-3.2,4.2-4.9c0.4-0.5,0.8-1,1.2-1.4	c0.6-0.7,1.2-1.4,1.9-2.2c0,0,0,0,0,0C8.4,8.2,5.6,4.1,2.8,0c0,0,0,0,0,0C5,0,7.1,0,9.2,0c0,0,0.1,0,0.1,0c1,1.5,2,2.9,3,4.4	c0.8,1.2,1.7,2.4,2.5,3.6c0,0,0,0,0,0.1c0.1-0.1,0.2-0.3,0.4-0.4c0.7-0.8,1.4-1.6,2.1-2.5c0.4-0.5,0.8-0.9,1.2-1.4	c0.9-1,1.8-2.1,2.7-3.1c0.2-0.2,0.4-0.4,0.6-0.7c0,0,0,0,0.1,0c0.6,0,1.2,0,1.8,0c0,0,0,0,0,0c-2.7,3.1-5.3,6.2-8,9.3	c0.1,0.1,0.2,0.3,0.3,0.4c0.7,1,1.4,2.1,2.1,3.1c0.2,0.3,0.4,0.6,0.7,1c0.7,1,1.4,2.1,2.1,3.1c0.7,1,1.3,1.9,2,2.9	c0.4,0.6,0.8,1.2,1.2,1.8c0.1,0.1,0.2,0.2,0.3,0.4c0,0,0,0-0.1,0c-2.1,0-4.2,0-6.3,0c0,0,0,0,0,0c-0.5-0.8-1.1-1.6-1.6-2.3	c-0.6-0.8-1.1-1.6-1.7-2.4c-0.8-1.2-1.7-2.4-2.5-3.7c0,0,0-0.1-0.1-0.1c0,0,0,0,0,0c-1.1,1.3-2.2,2.5-3.3,3.8	c-0.4,0.5-0.8,1-1.3,1.5c-0.3,0.4-0.6,0.7-1,1.1c-0.6,0.7-1.1,1.3-1.7,2c-0.1,0.1-0.1,0.1-0.2,0.2c0,0,0,0,0,0c0,0,0,0-0.1,0	C4,22,3.5,22,2.8,22C2.9,22,2.8,22,2.8,22C2.8,22,2.8,22,2.8,22z M21.7,20.6c-0.1-0.2-0.2-0.3-0.3-0.5c-0.3-0.4-0.6-0.9-0.9-1.3	c-0.3-0.4-0.5-0.7-0.8-1.1c-0.3-0.5-0.6-0.9-1-1.4c-0.4-0.6-0.8-1.2-1.2-1.8c-0.3-0.4-0.6-0.9-0.9-1.3c-0.3-0.4-0.6-0.9-0.9-1.3	c-0.6-0.9-1.2-1.7-1.8-2.6c-0.3-0.5-0.6-0.9-1-1.4c-1-1.4-2-2.8-2.9-4.2C9.7,3.5,9.5,3.1,9.2,2.7C8.9,2.3,8.6,1.9,8.3,1.5	c0,0,0,0-0.1,0c-0.9,0-1.9,0-2.8,0c0,0,0,0-0.1,0c0,0,0,0,0,0.1C5.5,1.7,5.7,1.8,5.8,2C6.4,2.9,7,3.8,7.7,4.7	c0.7,1.1,1.5,2.1,2.2,3.2c0.4,0.6,0.8,1.2,1.3,1.8c0.9,1.3,1.9,2.7,2.8,4c0.4,0.5,0.7,1.1,1.1,1.6c0.7,1,1.3,1.9,2,2.9	c0.3,0.4,0.5,0.8,0.8,1.2c0.3,0.4,0.6,0.8,0.8,1.2c0,0,0,0,0.1,0C19.8,20.6,20.7,20.6,21.7,20.6C21.7,20.6,21.7,20.6,21.7,20.6	C21.7,20.6,21.7,20.6,21.7,20.6C21.7,20.6,21.7,20.6,21.7,20.6z M24.3,22C24.3,22,24.3,22,24.3,22C24.3,22,24.3,22,24.3,22	C24.3,22,24.3,22,24.3,22C24.3,22,24.3,22,24.3,22c-2.1,0-4.3,0-6.4,0c0,0,0,0,0,0C20,22,22.2,22,24.3,22z M4.7,22	C4.7,22,4.6,22,4.7,22c-0.6,0-1.2,0-1.8,0c0,0,0,0-0.1,0C3.4,22,4.1,22,4.7,22z M21.7,20.6C21.7,20.6,21.7,20.6,21.7,20.6	C21.7,20.6,21.7,20.6,21.7,20.6C21.7,20.6,21.7,20.6,21.7,20.6z\"/> </svg>"
  url = "https://twitter.com/inside_r3"
  weight = 20

[[social]]
  name = "Corda Medium"
  pre = "<svg width=\"40\" height=\"24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><g clip-path=\"url(#clip0)\" fill=\"#FCFCFC\"><path d=\"M11.33 23.33c6.256 0 11.329-5.073 11.329-11.33S17.586.67 11.329.67 0 5.744 0 12s5.072 11.33 11.33 11.33zM29.401 22.964c3.129 0 5.665-4.909 5.665-10.964 0-6.055-2.536-10.964-5.665-10.964-3.128 0-5.664 4.909-5.664 10.964 0 6.055 2.536 10.964 5.665 10.964zM38.008 21.502c1.09 0 1.974-4.254 1.974-9.502 0-5.248-.884-9.502-1.974-9.502-1.09 0-1.973 4.254-1.973 9.502 0 5.248.883 9.502 1.973 9.502z\"/></g><defs><clipPath id=\"clip0\"><path fill=\"#fff\" transform=\"translate(0 .67)\" d=\"M0 0h40v22.659H0z\"/></clipPath></defs></svg>"
  url = "https://medium.com/corda"
  weight = 30

[[social]]
  name = "R3 Developers YouTube"
  pre = "<svg width=\"26\" height=\"18\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M25.7 5.44v-.013c-.127-1.671-.371-2.465-.371-2.465l-.004.006c-.016-.061-.03-.125-.05-.184l-.002-.012h-.001a3.503 3.503 0 00-2.81-2.358V.41C13.262-.495 3.758.38 3.758.38v.011A3.494 3.494 0 00.745 2.635L.74 2.633l-.024.077a3.47 3.47 0 00-.137.493c-.327 1.297-.985 4.8-.235 9.99l-.003-.001.196 1.236c.014.138.036.273.065.407l.01.063.004-.005c.012.054.022.108.037.162l.004.02h.001a3.495 3.495 0 003.181 2.497v.008s7.472.946 18.287 0l.002-.005a3.461 3.461 0 001.38-.363c.012-.006.023-.008.036-.014 1.067-.51 1.52-1.438 1.673-1.841.01-.022.018-.05.027-.077.025-.071.04-.123.04-.123h-.003c.006-.024.014-.04.02-.068l.037-.175a3.66 3.66 0 00.07-.353c.28-1.49.327-2.814.327-2.814h-.004c.224-2.58.13-4.75-.032-6.307zm-15.26 7.491V5.198l6.744 3.867-6.744 3.866z\" fill=\"#FCFCFC\"/></svg>"
  url = "https://www.youtube.com/channel/UCoOuUZatvIC1U65OisCrIKg/featured"
  weight = 40

[[social]]
  name = "Corda GitHub"
  pre = "<svg width=\"26\" height=\"24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M13.162 0C6.372 0 .865 5.507.865 12.297c0 5.432 3.546 10.034 8.374 11.693.603.076.83-.301.83-.603v-2.113c-3.395.755-4.15-1.66-4.15-1.66-.528-1.433-1.357-1.81-1.357-1.81-1.132-.754.075-.754.075-.754 1.207.075 1.886 1.282 1.886 1.282 1.132 1.886 2.867 1.358 3.546 1.056.075-.83.452-1.358.754-1.66-2.716-.301-5.582-1.357-5.582-6.11 0-1.358.452-2.414 1.282-3.32-.075-.226-.528-1.508.15-3.168 0 0 1.057-.302 3.396 1.282.98-.301 2.037-.377 3.093-.377s2.112.151 3.093.377C18.594 4.828 19.65 5.13 19.65 5.13c.679 1.66.226 2.942.15 3.244a4.88 4.88 0 011.283 3.32c0 4.752-2.867 5.733-5.582 6.035.452.377.83 1.131.83 2.263v3.395c0 .302.226.679.83.603a12.31 12.31 0 008.373-11.693C25.46 5.507 19.952 0 13.162 0z\" fill=\"#FCFCFC\"/></svg>"
  url = "https://github.com/corda/corda-runtime-os"
  weight = 45

[[social]]
  name = "R3 LinkedIn"
  pre = "<svg width=\"26\" height=\"24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M.853 7.806h5.38V24H.854V7.806zM3.579 0C1.737 0 .534 1.21.534 2.796c0 1.555 1.168 2.799 2.975 2.799h.034c1.877 0 3.046-1.244 3.046-2.799C6.554 1.21 5.42 0 3.579 0zm15.867 7.426c-2.856 0-4.136 1.57-4.85 2.673V7.806H9.213c.072 1.52 0 16.194 0 16.194h5.383v-9.044c0-.484.036-.967.177-1.314.39-.967 1.276-1.968 2.761-1.968 1.95 0 2.728 1.486 2.728 3.662V24h5.381v-9.286c0-4.974-2.654-7.288-6.197-7.288z\" fill=\"#FCFCFC\"/></svg>"
  url = "https://www.linkedin.com/company/r3cev-llc/"
  weight = 60

[[footer]]
  name = "Terms of Use"
  url = "https://www.r3.com/terms-of-use/"
  weight = 10

[[footer]]
  name = "Privacy Policy"
  url = "https://www.r3.com/privacy-policy/"
  weight = 20

[[footer]]
  name = "Trademark Policy"
  url = "https://www.r3.com/trademark-policy/"
  weight = 30

[[cenm-1-2]]
identifier = "cenm-1-2-cenm-releases"
name = "CENM releases"
weight = 70

[[cenm-1-2]]
identifier = "cenm-1-2-concepts-and-overview"
name = "Concepts and overview"
weight = 10

[[cenm-1-2]]
identifier = "cenm-1-2-configuration"
name = "Configuration"
weight = 210

[[cenm-1-2]]
identifier = "cenm-1-2-operations"
name = "Operations"
weight = 110

[[cenm-1-2]]
identifier = "cenm-1-2-public-key-infrastructure"
name = "Public key infrastructure"
weight = 300

[[cenm-1-2]]
identifier = "cenm-1-2-signing-plugin-samples"
name = "Signing plugin samples"
weight = 330

[[cenm-1-3]]
identifier = "cenm-1-3-cenm-releases"
name = "CENM releases"
weight = 70

[[cenm-1-3]]
identifier = "cenm-1-3-concepts-and-overview"
name = "Concepts and overview"
weight = 10

[[cenm-1-3]]
identifier = "cenm-1-3-configuration"
name = "Configuration"
weight = 210

[[cenm-1-3]]
identifier = "cenm-1-3-operations"
name = "Operations"
weight = 110

[[cenm-1-3]]
identifier = "cenm-1-3-public-key-infrastructure"
name = "Public key infrastructure"
weight = 300

[[cenm-1-3]]
identifier = "cenm-1-3-signing-plugin-samples"
name = "Signing plugin samples"
weight = 330

[[cenm-1-4]]
identifier = "cenm-1-4-cenm-releases"
name = "CENM releases"
weight = 70

[[cenm-1-4]]
identifier = "cenm-1-4-concepts-and-overview"
name = "Concepts and overview"
weight = 10

[[cenm-1-4]]
identifier = "cenm-1-4-configuration"
name = "Configuration"
weight = 210

[[cenm-1-4]]
identifier = "cenm-1-4-operations"
name = "Operations"
weight = 110

[[cenm-1-4]]
identifier = "cenm-1-4-public-key-infrastructure"
name = "Public key infrastructure"
weight = 300

[[cenm-1-4]]
identifier = "cenm-1-4-signing-plugin-samples"
name = "Signing plugin samples"
weight = 330

[[cenm-1-5]]
identifier = "cenm-1-5-cenm-releases"
name = "CENM releases"
weight = 70

[[cenm-1-5]]
identifier = "cenm-1-5-concepts-and-overview"
name = "Concepts and overview"
weight = 10

[[cenm-1-5]]
identifier = "cenm-1-5-configuration"
name = "Configuration"
weight = 210

[[cenm-1-5]]
identifier = "cenm-1-5-operations"
name = "Operations"
weight = 110

[[cenm-1-5]]
identifier = "cenm-1-5-public-key-infrastructure"
name = "Public key infrastructure"
weight = 300

[[cenm-1-5]]
identifier = "cenm-1-5-signing-plugin-samples"
name = "Signing plugin samples"
weight = 330

[[cenm-1-6]]
identifier = "cenm-1-6-cenm-releases"
name = "CENM releases"
weight = 70

[[cenm-1-6]]
identifier = "cenm-1-6-concepts-and-overview"
name = "Concepts and overview"
weight = 10

[[cenm-1-6]]
identifier = "cenm-1-6-configuration"
name = "Configuration"
weight = 210

[[cenm-1-6]]
identifier = "cenm-1-6-operations"
name = "Operations"
weight = 110

[[cenm-1-6]]
identifier = "cenm-1-6-public-key-infrastructure"
name = "Public key infrastructure"
weight = 300

[[cenm-1-6]]
identifier = "cenm-1-6-signing-plugin-samples"
name = "Signing plugin samples"
weight = 330

[[cenm-1-7]]
identifier = "cenm-1-7-cenm-releases"
name = "CENM releases"
weight = 70

[[cenm-1-7]]
identifier = "cenm-1-7-concepts-and-overview"
name = "Concepts and overview"
weight = 10

[[cenm-1-7]]
identifier = "cenm-1-7-configuration"
name = "Configuration"
weight = 210

[[cenm-1-7]]
identifier = "cenm-1-7-operations"
name = "Operations"
weight = 110

[[cenm-1-7]]
identifier = "cenm-1-7-public-key-infrastructure"
name = "Public key infrastructure"
weight = 300

[[cenm-1-7]]
identifier = "cenm-1-7-signing-plugin-samples"
name = "Signing plugin samples"
weight = 330

[[corda-enterprise-4-7]]
identifier = "corda-enterprise-4-7-notaries"
name = "Corda notaries"
weight = 35

[[corda-enterprise-4-7]]
identifier = "corda-enterprise-4-7-corda-networks"
name = "Corda networks"
weight = 40

[[corda-enterprise-4-7]]
identifier = "corda-enterprise-4-7-corda-nodes-operating"
name = "Operating a Corda node"
parent = "corda-enterprise-4-7-corda-nodes"
weight = 60

[[corda-enterprise-4-8]]
identifier = "corda-enterprise-4-8-notaries"
name = "Corda notaries"
weight = 35

[[corda-enterprise-4-8]]
identifier = "corda-enterprise-4-8-corda-networks"
name = "Corda networks"
weight = 40

[[corda-enterprise-4-8]]
identifier = "corda-enterprise-4-8-corda-nodes-operating"
name = "Operating a Corda node"
parent = "corda-enterprise-4-8-corda-nodes"
weight = 60

[[corda-enterprise-4-8]]
identifier = "corda-enterprise-4-8-notaries"
name = "Corda notaries"
weight = 35

[[corda-enterprise-4-8]]
identifier = "corda-enterprise-4-8-corda-networks"
name = "Corda networks"
weight = 40

[[corda-enterprise-4-8]]
identifier = "corda-enterprise-4-8-corda-nodes-operating"
name = "Operating a Corda node"
parent = "corda-enterprise-4-8-corda-nodes"
weight = 60

[[corda-enterprise-4-9]]
identifier = "corda-enterprise-4-9-notaries"
name = "Corda notaries"
weight = 35

[[corda-enterprise-4-9]]
identifier = "corda-enterprise-4-9-corda-networks"
name = "Corda networks"
weight = 40

[[corda-enterprise-4-9]]
identifier = "corda-enterprise-4-9-corda-nodes-operating"
name = "Operating a Corda node"
parent = "corda-enterprise-4-9-corda-nodes"
weight = 60

[[corda-enterprise-4-9]]
identifier = "corda-enterprise-4-9-notaries"
name = "Corda notaries"
weight = 35

[[corda-enterprise-4-9]]
identifier = "corda-enterprise-4-9-corda-networks"
name = "Corda networks"
weight = 40

[[corda-enterprise-4-9]]
identifier = "corda-enterprise-4-9-corda-nodes-operating"
name = "Operating a Corda node"
parent = "corda-enterprise-4-9-corda-nodes"
weight = 60

[[corda-community-4-9]]
identifier = "corda-community-4-9-upgrading"
name = "Upgrading CorDapps and nodes"
weight = 15
[[corda-community-4-9]]
identifier = "corda-community-4-9-corda-api"
name = "Corda API"
weight = 17
[[corda-community-4-9]]
identifier = "corda-community-4-9-development"
name = "Development"
weight = 20
[[corda-community-4-9]]
identifier = "corda-community-4-9-operations"
name = "Operations"
weight = 30
[[corda-community-4-9]]
identifier = "corda-community-4-9-contributing-index"
name = "Participate"
weight = 500

[[corda-enterprise-4-10]]
identifier = "corda-enterprise-4-10-notaries"
name = "Corda notaries"
weight = 35

[[corda-enterprise-4-10]]
identifier = "corda-enterprise-4-10-corda-networks"
name = "Corda networks"
weight = 40

[[corda-enterprise-4-10]]
identifier = "corda-enterprise-4-10-corda-nodes-operating"
name = "Operating a Corda node"
parent = "corda-enterprise-4-10-corda-nodes"
weight = 60

[[corda-enterprise-4-10]]
identifier = "corda-enterprise-4-10-notaries"
name = "Corda notaries"
weight = 35

[[corda-enterprise-4-10]]
identifier = "corda-enterprise-4-10-corda-networks"
name = "Corda networks"
weight = 40

[[corda-enterprise-4-10]]
identifier = "corda-enterprise-4-10-corda-nodes-operating"
name = "Operating a Corda node"
parent = "corda-enterprise-4-10-corda-nodes"
weight = 60

[[corda-community-4-10]]
identifier = "corda-community-4-10-upgrading"
name = "Upgrading CorDapps and nodes"
weight = 15

[[corda-community-4-10]]
identifier = "corda-community-4-10-corda-api"
name = "Corda API"
weight = 17

[[corda-community-4-10]]
identifier = "corda-community-4-10-development"
name = "Development"
weight = 20

[[corda-community-4-10]]
identifier = "corda-community-4-10-operations"
name = "Operations"
weight = 30

[[corda-community-4-10]]
identifier = "corda-community-4-10-contributing-index"
name = "Participate"
weight = 500

[[corda-enterprise-4-11]]
identifier = "corda-enterprise-4-11-notaries"
name = "Corda notaries"
weight = 35

[[corda-enterprise-4-11]]
identifier = "corda-enterprise-4-11-corda-networks"
name = "Corda networks"
weight = 40

[[corda-enterprise-4-11]]
identifier = "corda-enterprise-4-11-corda-nodes-operating"
name = "Operating a Corda node"
parent = "corda-enterprise-4-11-corda-nodes"
weight = 60

[[corda-enterprise-4-11]]
identifier = "corda-enterprise-4-11-notaries"
name = "Corda notaries"
weight = 35

[[corda-enterprise-4-11]]
identifier = "corda-enterprise-4-11-corda-networks"
name = "Corda networks"
weight = 40

[[corda-enterprise-4-11]]
identifier = "corda-enterprise-4-11-corda-nodes-operating"
name = "Operating a Corda node"
parent = "corda-enterprise-4-11-corda-nodes"
weight = 60

[[corda-community-4-11]]
identifier = "corda-community-4-11-upgrading"
name = "Upgrading CorDapps and nodes"
weight = 15

[[corda-community-4-11]]
identifier = "corda-community-4-11-corda-api"
name = "Corda API"
weight = 17

[[corda-community-4-11]]
identifier = "corda-community-4-11-development"
name = "Development"
weight = 20

[[corda-community-4-11]]
identifier = "corda-community-4-11-operations"
name = "Operations"
weight = 30

[[corda-community-4-11]]
identifier = "corda-community-4-11-contributing-index"
name = "Participate"
weight = 500

[[corda-enterprise-4-12]]
identifier = "corda-enterprise-4-12-notaries"
name = "Corda notaries"
weight = 35

[[corda-enterprise-4-12]]
identifier = "corda-enterprise-4-12-corda-networks"
name = "Corda networks"
weight = 40

[[corda-enterprise-4-12]]
identifier = "corda-enterprise-4-12-corda-nodes-operating"
name = "Operating a Corda node"
parent = "corda-enterprise-4-12-corda-nodes"
weight = 60

[[corda-enterprise-4-12]]
identifier = "corda-enterprise-4-12-notaries"
name = "Corda notaries"
weight = 35

[[corda-enterprise-4-12]]
identifier = "corda-enterprise-4-12-corda-networks"
name = "Corda networks"
weight = 40

[[corda-enterprise-4-12]]
identifier = "corda-enterprise-4-12-corda-nodes-operating"
name = "Operating a Corda node"
parent = "corda-enterprise-4-12-corda-nodes"
weight = 60

[[corda-community-4-12]]
identifier = "corda-community-4-12-upgrading"
name = "Upgrading CorDapps and nodes"
weight = 15

[[corda-community-4-12]]
identifier = "corda-community-4-12-corda-api"
name = "Corda API"
weight = 17

[[corda-community-4-12]]
identifier = "corda-community-4-12-development"
name = "Development"
weight = 20

[[corda-community-4-12]]
identifier = "corda-community-4-12-operations"
name = "Operations"
weight = 30

[[corda-community-4-12]]
identifier = "corda-community-4-12-contributing-index"
name = "Participate"
weight = 500

[[corda-enterprise-4-13]]
identifier = "corda-enterprise-4-13-notaries"
name = "Corda notaries"
weight = 35

[[corda-enterprise-4-13]]
identifier = "corda-enterprise-4-13-corda-networks"
name = "Corda networks"
weight = 40

[[corda-enterprise-4-13]]
identifier = "corda-enterprise-4-13-corda-nodes-operating"
name = "Operating a node"
parent = "corda-enterprise-4-12-corda-nodes"
weight = 60

[[corda-enterprise-4-13]]
identifier = "corda-enterprise-4-13-notaries"
name = "Corda notaries"
weight = 35

[[corda-enterprise-4-13]]
identifier = "corda-enterprise-4-13-corda-networks"
name = "Corda networks"
weight = 40

[[corda-enterprise-4-13]]
identifier = "corda-enterprise-4-13-corda-nodes-operating"
name = "Operating a node"
parent = "corda-enterprise-4-13-corda-nodes"
weight = 60

[[corda-community-4-13]]
identifier = "corda-community-4-13-upgrading"
name = "Upgrading CorDapps and nodes"
weight = 15

[[corda-community-4-13]]
identifier = "corda-community-4-13-corda-api"
name = "Corda API"
weight = 17

[[corda-community-4-13]]
identifier = "corda-community-4-13-development"
name = "Development"
weight = 20

[[corda-community-4-13]]
identifier = "corda-community-4-13-operations"
name = "Operations"
weight = 30

[[corda-community-4-13]]
identifier = "corda-community-4-13-contributing-index"
name = "Participate"
weight = 500

[[corda5]]
identifier = "corda5-rest-ref"
parent = "corda5-rest-api-reference"
name = "REST API reference"
weight = 2000
url = "/en/platform/corda/5.0/reference/rest-api/openapi.html"

[[corda51]]
identifier = "corda51-rest-ref"
parent = "corda51-rest-api-reference"
name = "REST API reference"
weight = 2000
url = "/en/platform/corda/5.1/reference/rest-api/openapi.html"

[[corda52]]
identifier = "corda52-rest-ref"
parent = "corda52-rest-api-reference"
name = "REST API reference"
weight = 2000
url = "/en/platform/corda/5.2/reference/rest-api/openapi.html"
